// Archivo generado a partir de las fuentes provistas; no editar cifras manualmente.
window.SCHOOLS_DATA=[
  {
    "cue": "608603",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA N°12 \"EDUARDO WILDE\"",
    "localidad": "GENERAL SAN MARTIN",
    "calle": "PROF. AGUSTÍN ROGELIO VIDAL",
    "nro": "3676",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 9,
    "matricula": 152,
    "varones": 84,
    "mujeres": 68,
    "periodo": "Anual 2026",
    "lat": -34.57285044,
    "lon": -58.54164919,
    "cueanexo": "060860300",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "617427",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA N°45",
    "localidad": "VILLA MAIPU",
    "calle": "ESTRADA ESQ. LAS HERAS",
    "nro": "2985",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 7,
    "matricula": 155,
    "varones": 97,
    "mujeres": 58,
    "periodo": "Anual 2026",
    "lat": -34.5735062,
    "lon": -58.52997694,
    "cueanexo": "061742700",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618647",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA N°57",
    "localidad": "VILLA MAIPU",
    "calle": "ESTRADA",
    "nro": "2400",
    "desfavorabilidad": "0",
    "categoria": "Tercera",
    "secciones": 6,
    "matricula": 131,
    "varones": 73,
    "mujeres": 58,
    "periodo": "Anual 2026",
    "lat": -34.57055594,
    "lon": -58.5243175,
    "cueanexo": "061864700",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "606133",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA N°7",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "BALCARCE (E/ BELGRANO Y ARTIGAS)",
    "nro": "277",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 21,
    "matricula": 452,
    "varones": 241,
    "mujeres": 211,
    "periodo": "Anual 2026",
    "lat": -34.55230816,
    "lon": -58.56027776,
    "cueanexo": "060613300",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618459",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº 48 \"VICTORIA OCAMPO\"",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "AMÉRICA",
    "nro": "151",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 279,
    "varones": 142,
    "mujeres": 137,
    "periodo": "Anual 2026",
    "lat": -34.55498186,
    "lon": -58.55357323,
    "cueanexo": "061845900",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "624772",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº 58",
    "localidad": "LOMA HERMOSA",
    "calle": "LAS CALAS",
    "nro": "6912",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 8,
    "matricula": 216,
    "varones": 100,
    "mujeres": 116,
    "periodo": "Anual 2026",
    "lat": -34.55231474,
    "lon": -58.5921312,
    "cueanexo": "062477200",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "607469",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº1 \"PERITO MORENO\"",
    "localidad": "GENERAL SAN MARTIN",
    "calle": "JUAREZ",
    "nro": "3626",
    "desfavorabilidad": "0",
    "categoria": "Primera",
    "secciones": 38,
    "matricula": 813,
    "varones": 381,
    "mujeres": 432,
    "periodo": "Anual 2026",
    "lat": -34.57941863,
    "lon": -58.53286966,
    "cueanexo": "060746900",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "609963",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº10",
    "localidad": "BARRIO PARQUE GENERAL SAN MARTIN",
    "calle": "LIBERTAD",
    "nro": "6845",
    "desfavorabilidad": "1",
    "categoria": "Segunda",
    "secciones": 21,
    "matricula": 488,
    "varones": 239,
    "mujeres": 249,
    "periodo": "Anual 2026",
    "lat": -34.55759755,
    "lon": -58.59453414,
    "cueanexo": "060996300",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "622976",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº11",
    "localidad": "GENERAL SAN MARTIN",
    "calle": "PROF. AGUSTÍN ROGELIO VIDAL",
    "nro": "3676",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 15,
    "matricula": 316,
    "varones": 156,
    "mujeres": 160,
    "periodo": "Anual 2026",
    "lat": -34.57275422,
    "lon": -58.54151321,
    "cueanexo": "062297600",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "611952",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº13 \"GENERAL MANUEL BELGRANO\"",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "LACROZE",
    "nro": "133",
    "desfavorabilidad": "0",
    "categoria": "Primera",
    "secciones": 69,
    "matricula": 1388,
    "varones": 631,
    "mujeres": 757,
    "periodo": "Anual 2026",
    "lat": -34.54835444,
    "lon": -58.55358895,
    "cueanexo": "061195200",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "609797",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº2 \"ARMADA ARGENTINA\"",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "CARLOS ECHAGUE",
    "nro": "7636",
    "desfavorabilidad": "1",
    "categoria": "Segunda",
    "secciones": 10,
    "matricula": 189,
    "varones": 94,
    "mujeres": 95,
    "periodo": "Anual 2026",
    "lat": -34.52953381,
    "lon": -58.57685438,
    "cueanexo": "060979700",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "622977",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº20",
    "localidad": "GENERAL SAN MARTIN",
    "calle": "PROF. AGUSTÍN ROGELIO VIDAL",
    "nro": "3676",
    "desfavorabilidad": "0",
    "categoria": "Primera",
    "secciones": 35,
    "matricula": 650,
    "varones": 302,
    "mujeres": 348,
    "periodo": "Anual 2026",
    "lat": -34.57266885,
    "lon": -58.54140268,
    "cueanexo": "062297700",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "610722",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº21 \"TUPAC AMARU\"",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "MITRE",
    "nro": "5035",
    "desfavorabilidad": "0",
    "categoria": "Primera",
    "secciones": 35,
    "matricula": 747,
    "varones": 342,
    "mujeres": 405,
    "periodo": "Anual 2026",
    "lat": -34.55412377,
    "lon": -58.56318308,
    "cueanexo": "061072200",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "600452",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº22 \"ROSARIO VERA PEÑALOZA\"",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "BALCARCE",
    "nro": "3469",
    "desfavorabilidad": "0",
    "categoria": "Primera",
    "secciones": 36,
    "matricula": 762,
    "varones": 334,
    "mujeres": 428,
    "periodo": "Anual 2026",
    "lat": -34.55420598,
    "lon": -58.56261326,
    "cueanexo": "060045200",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "614757",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº23",
    "localidad": "VILLA GRANADEROS DE SAN MARTIN",
    "calle": "AV.FLEMING",
    "nro": "3956",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 15,
    "matricula": 285,
    "varones": 133,
    "mujeres": 152,
    "periodo": "Anual 2026",
    "lat": -34.54021781,
    "lon": -58.52844799,
    "cueanexo": "061475700",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "617353",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº24",
    "localidad": "BARRIO PARQUE GENERAL SAN MARTIN",
    "calle": "SARMIENTO E/ GÜEMES Y SAN MARTÍN",
    "nro": "1352",
    "desfavorabilidad": "1",
    "categoria": "Segunda",
    "secciones": 16,
    "matricula": 394,
    "varones": 199,
    "mujeres": 195,
    "periodo": "Anual 2026",
    "lat": -34.55503051,
    "lon": -58.60315741,
    "cueanexo": "061735300",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "617942",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº25",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "MALVINAS ARGENTINAS",
    "nro": "8361",
    "desfavorabilidad": "1",
    "categoria": "Segunda",
    "secciones": 15,
    "matricula": 327,
    "varones": 168,
    "mujeres": 159,
    "periodo": "Anual 2026",
    "lat": -34.53223094,
    "lon": -58.58666466,
    "cueanexo": "061794200",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "617941",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº26 \"LUIS ALBERTO SPINETTA\"",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "AVDA. 9 DE JULIO ESQ. MONACO",
    "nro": "6351",
    "desfavorabilidad": "1",
    "categoria": "Segunda",
    "secciones": 17,
    "matricula": 477,
    "varones": 233,
    "mujeres": 244,
    "periodo": "Anual 2026",
    "lat": -34.54931502,
    "lon": -58.58024165,
    "cueanexo": "061794100",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618651",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº27",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "AGUSTÍN ÁLVAREZ",
    "nro": "2327",
    "desfavorabilidad": "1",
    "categoria": "Segunda",
    "secciones": 10,
    "matricula": 211,
    "varones": 108,
    "mujeres": 103,
    "periodo": "Anual 2026",
    "lat": -34.55406051,
    "lon": -58.54205079,
    "cueanexo": "061865100",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618128",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº28",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "RIO NEGRO E/ LACROZE Y BOULEVARD",
    "nro": "350",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 8,
    "matricula": 172,
    "varones": 108,
    "mujeres": 64,
    "periodo": "Anual 2026",
    "lat": -34.53702023,
    "lon": -58.56703775,
    "cueanexo": "061812800",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618882",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº29",
    "localidad": "SAN ANDRES",
    "calle": "MISIONES",
    "nro": "3680",
    "desfavorabilidad": "0",
    "categoria": "Tercera",
    "secciones": 6,
    "matricula": 83,
    "varones": 45,
    "mujeres": 38,
    "periodo": "Anual 2026",
    "lat": -34.56243912,
    "lon": -58.55157959,
    "cueanexo": "061888200",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "606080",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº3 \"LEOPOLDO LUGONES\"",
    "localidad": "SAN ANDRES",
    "calle": "JOSÉ M CAMPOS ESQ. SAN JUAN",
    "nro": "1918",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 15,
    "matricula": 357,
    "varones": 176,
    "mujeres": 181,
    "periodo": "Anual 2026",
    "lat": -34.55902719,
    "lon": -58.53682637,
    "cueanexo": "060608000",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618123",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº30",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "ESPAÑA",
    "nro": "5640",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 6,
    "matricula": 158,
    "varones": 80,
    "mujeres": 78,
    "periodo": "Anual 2026",
    "lat": -34.56105267,
    "lon": -58.58087999,
    "cueanexo": "061812300",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618126",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº31",
    "localidad": "SAN ANDRES",
    "calle": "SAENZ PEÑA",
    "nro": "2953",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 176,
    "varones": 104,
    "mujeres": 72,
    "periodo": "Anual 2026",
    "lat": -34.56849165,
    "lon": -58.5358219,
    "cueanexo": "061812600",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618132",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº32",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "PROFESOR SIMON Y QUINTANA",
    "nro": "1439",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 208,
    "varones": 108,
    "mujeres": 100,
    "periodo": "Anual 2026",
    "lat": -34.53398588,
    "lon": -58.55341762,
    "cueanexo": "061813200",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "617940",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº33",
    "localidad": "VILLA GRANADEROS DE SAN MARTIN",
    "calle": "MENDOZA",
    "nro": "1069",
    "desfavorabilidad": "1",
    "categoria": "Tercera",
    "secciones": 12,
    "matricula": 168,
    "varones": 88,
    "mujeres": 80,
    "periodo": "Anual 2026",
    "lat": -34.55447707,
    "lon": -58.52263299,
    "cueanexo": "061794000",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "617943",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº35",
    "localidad": "VILLA MAIPU",
    "calle": "JULIO A. ROCA",
    "nro": "2400",
    "desfavorabilidad": "1",
    "categoria": "Segunda",
    "secciones": 6,
    "matricula": 153,
    "varones": 81,
    "mujeres": 72,
    "periodo": "Anual 2026",
    "lat": -34.56102287,
    "lon": -58.52371952,
    "cueanexo": "061794300",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "620277",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº36",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "SAENZ PEÑA",
    "nro": "3645",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 234,
    "varones": 128,
    "mujeres": 106,
    "periodo": "Anual 2026",
    "lat": -34.54389137,
    "lon": -58.5772271,
    "cueanexo": "062027700",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618884",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº37",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "CUBA",
    "nro": "4450",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 11,
    "matricula": 195,
    "varones": 117,
    "mujeres": 78,
    "periodo": "Anual 2026",
    "lat": -34.55766762,
    "lon": -58.57361238,
    "cueanexo": "061888400",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618650",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº38",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "ESTRADA",
    "nro": "9060",
    "desfavorabilidad": "1",
    "categoria": "Segunda",
    "secciones": 13,
    "matricula": 280,
    "varones": 133,
    "mujeres": 147,
    "periodo": "Anual 2026",
    "lat": -34.51267775,
    "lon": -58.5783493,
    "cueanexo": "061865000",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618648",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº39",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "GENERAL FRÍAS",
    "nro": "7560",
    "desfavorabilidad": "1",
    "categoria": "Segunda",
    "secciones": 15,
    "matricula": 397,
    "varones": 204,
    "mujeres": 193,
    "periodo": "Anual 2026",
    "lat": -34.5314254,
    "lon": -58.57847792,
    "cueanexo": "061864800",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "609738",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº4 \"RICARDO ROJAS\"",
    "localidad": "BARRIO PARQUE GENERAL SAN MARTIN",
    "calle": "DIAG. 96 -ALSINA",
    "nro": "4945",
    "desfavorabilidad": "1",
    "categoria": "Segunda",
    "secciones": 20,
    "matricula": 385,
    "varones": 201,
    "mujeres": 184,
    "periodo": "Anual 2026",
    "lat": -34.5698547,
    "lon": -58.56484743,
    "cueanexo": "060973800",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618129",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº40",
    "localidad": "GENERAL SAN MARTIN",
    "calle": "OMBU ESQ. TUNUYAN",
    "nro": "1490",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 6,
    "matricula": 173,
    "varones": 80,
    "mujeres": 93,
    "periodo": "Anual 2026",
    "lat": -34.59196585,
    "lon": -58.5478286,
    "cueanexo": "061812900",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618652",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº42",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "JOSÉ INGENIEROS",
    "nro": "4606",
    "desfavorabilidad": "1",
    "categoria": "Segunda",
    "secciones": 10,
    "matricula": 290,
    "varones": 142,
    "mujeres": 148,
    "periodo": "Anual 2026",
    "lat": -34.54428097,
    "lon": -58.59046561,
    "cueanexo": "061865200",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618991",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº43",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "PATAGONIA Y JOSÉ INGENIEROS",
    "nro": "7493",
    "desfavorabilidad": "1",
    "categoria": "Segunda",
    "secciones": 9,
    "matricula": 273,
    "varones": 129,
    "mujeres": 144,
    "periodo": "Anual 2026",
    "lat": -34.544491,
    "lon": -58.59071711,
    "cueanexo": "061899100",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618131",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº44",
    "localidad": "BARRIO PARQUE GENERAL SAN MARTIN",
    "calle": "90 E/15 Y 17",
    "nro": "750",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 186,
    "varones": 85,
    "mujeres": 101,
    "periodo": "Anual 2026",
    "lat": -34.54483012,
    "lon": -58.53105599,
    "cueanexo": "061813100",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "617939",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº46",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "DIAG. 180 E/ ARTIGAS Y S. DEL ESTERO",
    "nro": "3528",
    "desfavorabilidad": "1",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 277,
    "varones": 132,
    "mujeres": 145,
    "periodo": "Anual 2026",
    "lat": -34.53686492,
    "lon": -58.58209741,
    "cueanexo": "061793900",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618649",
    "cueanexo": "061864900",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº47",
    "gestion": "Estatal",
    "modalidad": "Técnico Profesional",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "C. ECHAGÜE",
    "nro": "8287",
    "desfavorabilidad": "1",
    "categoria": "Segunda",
    "secciones": 1,
    "matricula": 12,
    "varones": 9,
    "mujeres": 3,
    "periodo": "Anual 2026",
    "lat": -34.52456228,
    "lon": -58.58201708,
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Modalidad Técnico Profesional Secundaria - Gestión estatal 18-08-2026.xlsx"
  },
  {
    "cue": "617938",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº49",
    "localidad": "GENERAL SAN MARTIN",
    "calle": "BELGRANO E/ URUGUAY Y SAN MARTÍN",
    "nro": "3740",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 286,
    "varones": 137,
    "mujeres": 149,
    "periodo": "Anual 2026",
    "lat": -34.57762263,
    "lon": -58.53704985,
    "cueanexo": "061793800",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "600186",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº5 \"DR. BERNARDO DE MONTEAGUDO\"",
    "localidad": "VILLA LYNCH",
    "calle": "ESPORA",
    "nro": "4022",
    "desfavorabilidad": "0",
    "categoria": "Tercera",
    "secciones": 6,
    "matricula": 137,
    "varones": 69,
    "mujeres": 68,
    "periodo": "Anual 2026",
    "lat": -34.5908906,
    "lon": -58.52624383,
    "cueanexo": "060018600",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618653",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº50 \"SOLDADO ANDRÉS FOLCH\"",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "LIBERTADOR GENERAL SAN MARTÍN",
    "nro": "5810",
    "desfavorabilidad": "1",
    "categoria": "Segunda",
    "secciones": 6,
    "matricula": 150,
    "varones": 77,
    "mujeres": 73,
    "periodo": "Anual 2026",
    "lat": -34.55782559,
    "lon": -58.58186421,
    "cueanexo": "061865300",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618646",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº51",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "PROFESOR AGUER",
    "nro": "6641",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 267,
    "varones": 118,
    "mujeres": 149,
    "periodo": "Anual 2026",
    "lat": -34.53873458,
    "lon": -58.57362935,
    "cueanexo": "061864600",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618130",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº52 \"DOCTOR RENÉ FAVALORO\"",
    "localidad": "VILLA LIBERTAD",
    "calle": "INFANTA ISABEL",
    "nro": "2649",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 233,
    "varones": 125,
    "mujeres": 108,
    "periodo": "Anual 2026",
    "lat": -34.58732462,
    "lon": -58.56240305,
    "cueanexo": "061813000",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618127",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº53",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "BARTOLOME MITRE E/ CUBA Y ENSENADA",
    "nro": "5473",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 6,
    "matricula": 155,
    "varones": 76,
    "mujeres": 79,
    "periodo": "Anual 2026",
    "lat": -34.55100767,
    "lon": -58.56724767,
    "cueanexo": "061812700",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "617426",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº54",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "JOSÉ HERNANDEZ",
    "nro": "3897",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 9,
    "matricula": 272,
    "varones": 122,
    "mujeres": 150,
    "periodo": "Anual 2026",
    "lat": -34.55934683,
    "lon": -58.56259783,
    "cueanexo": "061742600",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "618124",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº55",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "BOULEVARD BALLESTER",
    "nro": "554",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 234,
    "varones": 120,
    "mujeres": 114,
    "periodo": "Anual 2026",
    "lat": -34.543595,
    "lon": -58.5582144,
    "cueanexo": "061812400",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "617428",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº56",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "INGENIERO HUERGO E/ SAENZ Y MEDRANO",
    "nro": "8630",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 8,
    "matricula": 218,
    "varones": 112,
    "mujeres": 106,
    "periodo": "Anual 2026",
    "lat": -34.51697783,
    "lon": -58.57742355,
    "cueanexo": "061742800",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "611546",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº6 \"ALFONSINA STORNI\"",
    "localidad": "BILLINGHURST",
    "calle": "SAN LORENZO",
    "nro": "5951",
    "desfavorabilidad": "0",
    "categoria": "Primera",
    "secciones": 32,
    "matricula": 600,
    "varones": 293,
    "mujeres": 307,
    "periodo": "Anual 2026",
    "lat": -34.57647564,
    "lon": -58.57564594,
    "cueanexo": "061154600",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "609792",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA Nº8 \"ESTEBAN ECHEVERRÍA\"",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "RAWSON ESQUINA ITALIA",
    "nro": "1918",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 21,
    "matricula": 380,
    "varones": 211,
    "mujeres": 169,
    "periodo": "Anual 2026",
    "lat": -34.53064678,
    "lon": -58.56406762,
    "cueanexo": "060979200",
    "gestion": "Estatal",
    "modalidad": "Común",
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Secundaria",
    "source": "Base estatal común validada"
  },
  {
    "cue": "611553",
    "cueanexo": "061155300",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA TÉCNICA Nº1 \"MANUEL BELGRANO\"",
    "gestion": "Estatal",
    "modalidad": "Técnico Profesional",
    "localidad": "GENERAL SAN MARTIN",
    "calle": "INTENDENTE CAMPOS E/ MORENO Y BELGRANO",
    "nro": "1950",
    "desfavorabilidad": "0",
    "categoria": "Primera",
    "secciones": 0,
    "matricula": 0,
    "varones": 0,
    "mujeres": 0,
    "periodo": "Nueva",
    "lat": -34.5778489,
    "lon": -58.53640251,
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Técnico Profesional",
    "source": "Modalidad Técnico Profesional Secundaria - Gestión estatal 18-08-2026.xlsx"
  },
  {
    "cue": "601624",
    "cueanexo": "060162400",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA TÉCNICA Nº2 \"ALEMANIA\"",
    "gestion": "Estatal",
    "modalidad": "Técnico Profesional",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "PACIFICO RODRIGUEZ",
    "nro": "5650",
    "desfavorabilidad": "0",
    "categoria": "Primera",
    "secciones": 41,
    "matricula": 957,
    "varones": 602,
    "mujeres": 355,
    "periodo": "Anual 2026",
    "lat": -34.54395868,
    "lon": -58.56136058,
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Técnico Profesional",
    "source": "Modalidad Técnico Profesional Secundaria - Gestión estatal 18-08-2026.xlsx"
  },
  {
    "cue": "607470",
    "cueanexo": "060747000",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA TÉCNICA Nº3 \"PREFECTURA NAVAL ARGENTINA\"",
    "gestion": "Estatal",
    "modalidad": "Técnico Profesional",
    "localidad": "GENERAL SAN MARTIN",
    "calle": "AV 101(EX RICARDO BALBIN)",
    "nro": "2281",
    "desfavorabilidad": "0",
    "categoria": "Primera",
    "secciones": 32,
    "matricula": 785,
    "varones": 427,
    "mujeres": 358,
    "periodo": "Anual 2026",
    "lat": -34.57872865,
    "lon": -58.54391324,
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Técnico Profesional",
    "source": "Modalidad Técnico Profesional Secundaria - Gestión estatal 18-08-2026.xlsx"
  },
  {
    "cue": "611554",
    "cueanexo": "061155400",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA TÉCNICA Nº4 \"ING. EMILIO MITRE\"",
    "gestion": "Estatal",
    "modalidad": "Técnico Profesional",
    "localidad": "GENERAL SAN MARTIN",
    "calle": "SAN MARTÍN",
    "nro": "1714",
    "desfavorabilidad": "0",
    "categoria": "Primera",
    "secciones": 63,
    "matricula": 1440,
    "varones": 1004,
    "mujeres": 436,
    "periodo": "Anual 2026",
    "lat": -34.58016725,
    "lon": -58.5351479,
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Técnico Profesional",
    "source": "Modalidad Técnico Profesional Secundaria - Gestión estatal 18-08-2026.xlsx"
  },
  {
    "cue": "611547",
    "cueanexo": "061154700",
    "nombre": "ESCUELA DE EDUCACIÓN SECUNDARIA TÉCNICA Nº5 \"GALILEO GALILEI\"",
    "gestion": "Estatal",
    "modalidad": "Técnico Profesional",
    "localidad": "GENERAL SAN MARTIN",
    "calle": "AVDA. EVA PERÓN",
    "nro": "4541",
    "desfavorabilidad": "0",
    "categoria": "Primera",
    "secciones": 38,
    "matricula": 994,
    "varones": 604,
    "mujeres": 390,
    "periodo": "Anual 2026",
    "lat": -34.56997089,
    "lon": -58.5729356,
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Dirección Provincial de Educación Técnico Profesional",
    "source": "Modalidad Técnico Profesional Secundaria - Gestión estatal 18-08-2026.xlsx"
  },
  {
    "cue": "622906",
    "cueanexo": "062290600",
    "nombre": "ESCUELA SECUNDARIA TÉCNICA DE LA UNSAM",
    "gestion": "Estatal",
    "modalidad": "Técnico Profesional",
    "localidad": "GENERAL SAN MARTIN",
    "calle": "AVENIDA 25 DE MAYO Y CATALINA DE BOYLE",
    "nro": "S/N",
    "desfavorabilidad": "0",
    "categoria": "S/Datos",
    "secciones": 0,
    "matricula": 0,
    "varones": 0,
    "mujeres": 0,
    "periodo": "Nueva",
    "lat": -34.53729621,
    "lon": -58.5969127,
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Ministerio de Educación de la Nación",
    "source": "Modalidad Técnico Profesional Secundaria - Gestión estatal 18-08-2026.xlsx"
  },
  {
    "cue": "622662",
    "cueanexo": "062266200",
    "nombre": "ESCUELA TECNOLÓGICA WARNER VON SIEMENS",
    "gestion": "Estatal",
    "modalidad": "Técnico Profesional",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "MARTÍN LANGE (CALLE 77)",
    "nro": "4377",
    "desfavorabilidad": "0",
    "categoria": "S/Datos",
    "secciones": 7,
    "matricula": 144,
    "varones": 130,
    "mujeres": 14,
    "periodo": "Anual 2026",
    "lat": -34.55645215,
    "lon": -58.55527928,
    "turnos": "",
    "subvencion": "Oficial",
    "dependencia": "Ministerio de Educación de la Nación",
    "source": "Modalidad Técnico Profesional Secundaria - Gestión estatal 18-08-2026.xlsx"
  },
  {
    "cue": "619921",
    "cueanexo": "061992100",
    "nombre": "CASA DEL SOL",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "VILLA LIBERTAD",
    "calle": "AV.TRIUNVIRATO",
    "nro": "2677",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 18,
    "matricula": 510,
    "varones": 255,
    "mujeres": 255,
    "periodo": "Anual 2026",
    "lat": -34.5889736,
    "lon": -58.5647933,
    "turnos": "",
    "subvencion": "Subvención parcial 80%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "609800",
    "cueanexo": "060980000",
    "nombre": "COLEGIO ALMAFUERTE",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "EMILIO MITRE",
    "nro": "8105",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 414,
    "varones": 189,
    "mujeres": 225,
    "periodo": "Anual 2026",
    "lat": -34.51928593,
    "lon": -58.57272346,
    "turnos": "",
    "subvencion": "Subvención parcial 80%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "603331",
    "cueanexo": "060333100",
    "nombre": "COLEGIO EYMARD",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "BARRIO PARQUE GENERAL SAN MARTIN",
    "calle": "JOSÉ C. PAZ",
    "nro": "4801",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 269,
    "varones": 129,
    "mujeres": 140,
    "periodo": "Anual 2026",
    "lat": -34.57870709,
    "lon": -58.55342216,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "619914",
    "cueanexo": "061991400",
    "nombre": "COLEGIO JOSÉ HERNANDEZ",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "PROF. AGUER",
    "nro": "5036",
    "desfavorabilidad": "0",
    "categoria": "Primera",
    "secciones": 54,
    "matricula": 1681,
    "varones": 749,
    "mujeres": 932,
    "periodo": "Anual 2026",
    "lat": -34.55078571,
    "lon": -58.55873543,
    "turnos": "",
    "subvencion": "Subvención parcial 80%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "619915",
    "cueanexo": "061991500",
    "nombre": "COLEGIO LA SAGRADA FAMILIA",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "BILLINGHURST",
    "calle": "MORENO 133",
    "nro": "4247",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 6,
    "matricula": 183,
    "varones": 78,
    "mujeres": 105,
    "periodo": "Anual 2026",
    "lat": -34.57459407,
    "lon": -58.57406174,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "619536",
    "cueanexo": "061953600",
    "nombre": "COLEGIO MARIA INMACULADA",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "GENERAL SAN MARTIN",
    "calle": "HONORIO SENET",
    "nro": "2051",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 6,
    "matricula": 174,
    "varones": 86,
    "mujeres": 88,
    "periodo": "Anual 2026",
    "lat": -34.58595991,
    "lon": -58.54811298,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "619916",
    "cueanexo": "061991600",
    "nombre": "COLEGIO NUESTRA SEÑORA DE LUJAN",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "CHACABUCO",
    "nro": "3662",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 6,
    "matricula": 354,
    "varones": 152,
    "mujeres": 202,
    "periodo": "Anual 2026",
    "lat": -34.55135658,
    "lon": -58.56979283,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "621831",
    "cueanexo": "062183100",
    "nombre": "COLEGIO RUBEN DARIO",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "AMERICA",
    "nro": "3576",
    "desfavorabilidad": "0",
    "categoria": "Tercera",
    "secciones": 11,
    "matricula": 262,
    "varones": 107,
    "mujeres": 155,
    "periodo": "Anual 2026",
    "lat": -34.55950279,
    "lon": -58.54776016,
    "turnos": "",
    "subvencion": "Sin Subvención",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "601627",
    "cueanexo": "060162700",
    "nombre": "ESCUELA HÖLTERS",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "INDEPENDENCIA",
    "nro": "836",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 16,
    "matricula": 368,
    "varones": 148,
    "mujeres": 220,
    "periodo": "Anual 2026",
    "lat": -34.54286263,
    "lon": -58.56444523,
    "turnos": "",
    "subvencion": "Subvención parcial 40%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "617036",
    "cueanexo": "061703600",
    "nombre": "HOGAR ESCUELA CRISTIANA F.E.",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "VICENTE LOPEZ",
    "nro": "259",
    "desfavorabilidad": "0",
    "categoria": "Tercera",
    "secciones": 6,
    "matricula": 169,
    "varones": 80,
    "mujeres": 89,
    "periodo": "Anual 2026",
    "lat": -34.55372389,
    "lon": -58.55785679,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "609443",
    "cueanexo": "060944300",
    "nombre": "INSTITUTO AGUSTINIANO",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "SAN ANDRES",
    "calle": "SALGUERO",
    "nro": "2778",
    "desfavorabilidad": "0",
    "categoria": "Primera",
    "secciones": 30,
    "matricula": 1016,
    "varones": 501,
    "mujeres": 515,
    "periodo": "Anual 2026",
    "lat": -34.57025928,
    "lon": -58.5441562,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "616064",
    "cueanexo": "061606400",
    "nombre": "INSTITUTO ALFONSINA STORNI",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "BIARRITZ E/A. DEL VALLE Y A.STORNI",
    "nro": "3349",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 6,
    "matricula": 207,
    "varones": 82,
    "mujeres": 125,
    "periodo": "Anual 2026",
    "lat": -34.54396713,
    "lon": -58.57387365,
    "turnos": "",
    "subvencion": "Subvención parcial 60%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "606124",
    "cueanexo": "060612400",
    "nombre": "INSTITUTO BALLESTER",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "SAN MARTÍN",
    "nro": "444",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 23,
    "matricula": 435,
    "varones": 188,
    "mujeres": 247,
    "periodo": "Anual 2026",
    "lat": -34.54870622,
    "lon": -58.5593943,
    "turnos": "",
    "subvencion": "Sin Subvención",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "609795",
    "cueanexo": "060979500",
    "nombre": "INSTITUTO CONCORDIA",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "LIBERTAD",
    "nro": "7200",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 8,
    "matricula": 227,
    "varones": 103,
    "mujeres": 124,
    "periodo": "Anual 2026",
    "lat": -34.52977769,
    "lon": -58.57000255,
    "turnos": "",
    "subvencion": "Subvención parcial 70%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "619534",
    "cueanexo": "061953400",
    "nombre": "INSTITUTO EMILIO LAMARCA",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "CONGRESO",
    "nro": "364",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 6,
    "matricula": 132,
    "varones": 56,
    "mujeres": 76,
    "periodo": "Anual 2026",
    "lat": -34.55794764,
    "lon": -58.55113414,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "609439",
    "cueanexo": "060943900",
    "nombre": "INSTITUTO EVANGÉLICO EL BUEN PASTOR",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "VILLA JUAN MARTIN DE PUEYRREDON",
    "calle": "123 - GENERAL MANUEL BELGRANO",
    "nro": "3747",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 6,
    "matricula": 151,
    "varones": 71,
    "mujeres": 80,
    "periodo": "Anual 2026",
    "lat": -34.57436204,
    "lon": -58.56577127,
    "turnos": "",
    "subvencion": "Subvención parcial 80%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "607306",
    "cueanexo": "060730600",
    "nombre": "INSTITUTO HÖLTERS",
    "gestion": "Privada",
    "modalidad": "Técnico Profesional",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "INDEPENDENCIA",
    "nro": "5886",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 10,
    "matricula": 209,
    "varones": 143,
    "mujeres": 66,
    "periodo": "Anual 2026",
    "lat": -34.54277797,
    "lon": -58.56462686,
    "turnos": "",
    "subvencion": "Subvención parcial 40%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Modalidad Técnico Profesional Secundaria - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "622438",
    "cueanexo": "062243800",
    "nombre": "INSTITUTO INCORPORADO SAN ANDRES",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "SAN JOSÉ DE FLORES",
    "nro": "6039",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 336,
    "varones": 154,
    "mujeres": 182,
    "periodo": "Anual 2026",
    "lat": -34.54891131,
    "lon": -58.57516226,
    "turnos": "",
    "subvencion": "Subvención parcial 80%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "606127",
    "cueanexo": "060612700",
    "nombre": "INSTITUTO JOSÉ HERNANDEZ",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "PROFESOR AGUER",
    "nro": "5059",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 18,
    "matricula": 439,
    "varones": 196,
    "mujeres": 243,
    "periodo": "Anual 2026",
    "lat": -34.55047277,
    "lon": -58.55880681,
    "turnos": "",
    "subvencion": "Subvención parcial 80%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "619535",
    "cueanexo": "061953500",
    "nombre": "INSTITUTO JOSÉ MANUEL ESTRADA",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "GENERAL SAN MARTIN",
    "calle": "DARDO ROCHA E/ LINCOLN Y MORENO",
    "nro": "1853",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 199,
    "varones": 84,
    "mujeres": 115,
    "periodo": "Anual 2026",
    "lat": -34.58375826,
    "lon": -58.54114859,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "609400",
    "cueanexo": "060940000",
    "nombre": "INSTITUTO LA SALLE",
    "gestion": "Privada",
    "modalidad": "Técnico Profesional",
    "localidad": "BARRIO PARQUE GENERAL SAN MARTIN",
    "calle": "AVENIDA EVA PERÓN",
    "nro": "3151",
    "desfavorabilidad": "0",
    "categoria": "Primera",
    "secciones": 28,
    "matricula": 943,
    "varones": 597,
    "mujeres": 346,
    "periodo": "Anual 2026",
    "lat": -34.57861029,
    "lon": -58.56186539,
    "turnos": "",
    "subvencion": "Subvención parcial 80%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Modalidad Técnico Profesional Secundaria - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "619920",
    "cueanexo": "061992000",
    "nombre": "INSTITUTO LIBERTAD",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "VILLA LIBERTAD",
    "calle": "INFANTA ISABEL",
    "nro": "2444",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 304,
    "varones": 134,
    "mujeres": 170,
    "periodo": "Anual 2026",
    "lat": -34.58942873,
    "lon": -58.56040052,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "615760",
    "cueanexo": "061576000",
    "nombre": "INSTITUTO MAIPU",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "GENERAL SAN MARTIN",
    "calle": "58 (PUEYRREDÓN)",
    "nro": "3105",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 346,
    "varones": 154,
    "mujeres": 192,
    "periodo": "Anual 2026",
    "lat": -34.57065762,
    "lon": -58.53537846,
    "turnos": "",
    "subvencion": "Subvención parcial 80%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "608571",
    "cueanexo": "060857100",
    "nombre": "INSTITUTO MARIANO MORENO",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "GENERAL SAN MARTIN",
    "calle": "R. CARRILLO",
    "nro": "2332",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 15,
    "matricula": 367,
    "varones": 174,
    "mujeres": 193,
    "periodo": "Anual 2026",
    "lat": -34.57447618,
    "lon": -58.54042453,
    "turnos": "",
    "subvencion": "Subvención parcial 80%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "606074",
    "cueanexo": "060607400",
    "nombre": "INSTITUTO NUESTRA SEÑORA DE LA MERCED",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "SAN ANDRES",
    "calle": "JUNÍN",
    "nro": "2641",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 18,
    "matricula": 397,
    "varones": 175,
    "mujeres": 222,
    "periodo": "Anual 2026",
    "lat": -34.56509271,
    "lon": -58.53567791,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "622227",
    "cueanexo": "062222700",
    "nombre": "INSTITUTO NUESTRA SEÑORA DE LA MERCED",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "LAMADRID",
    "nro": "2542",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 271,
    "varones": 118,
    "mujeres": 153,
    "periodo": "Anual 2026",
    "lat": -34.54563322,
    "lon": -58.55657924,
    "turnos": "",
    "subvencion": "Subvención parcial 70%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "616234",
    "cueanexo": "061623400",
    "nombre": "INSTITUTO NUESTRA SEÑORA DEL LIBANO",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "VILLA LYNCH",
    "calle": "AV. 10 REP. DEL LIBANO Y MONTEAGUDO",
    "nro": "4031",
    "desfavorabilidad": "0",
    "categoria": "Tercera",
    "secciones": 6,
    "matricula": 168,
    "varones": 80,
    "mujeres": 88,
    "periodo": "Anual 2026",
    "lat": -34.59160573,
    "lon": -58.5252817,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "620059",
    "cueanexo": "062005900",
    "nombre": "INSTITUTO PRIVADO DR. MANUEL BELGRANO",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "ITUZAINGO",
    "nro": "2420",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 6,
    "matricula": 168,
    "varones": 92,
    "mujeres": 76,
    "periodo": "Anual 2026",
    "lat": -34.54146091,
    "lon": -58.55938312,
    "turnos": "",
    "subvencion": "Subvención parcial 70%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "609945",
    "cueanexo": "060994500",
    "nombre": "INSTITUTO REMEDIOS DE ESCALADA DE SAN MARTIN",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "BARRIO PARQUE GENERAL SAN MARTIN",
    "calle": "SOLDADO FOLCH",
    "nro": "6527",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 10,
    "matricula": 274,
    "varones": 127,
    "mujeres": 147,
    "periodo": "Anual 2026",
    "lat": -34.55145671,
    "lon": -58.58689217,
    "turnos": "",
    "subvencion": "Subvención parcial 80%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "611482",
    "cueanexo": "061148200",
    "nombre": "INSTITUTO SAN ANTONIO DE PADUA",
    "gestion": "Privada",
    "modalidad": "Técnico Profesional",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "CALLE 71 (EX PROF. AGUER)",
    "nro": "7201",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 25,
    "matricula": 713,
    "varones": 407,
    "mujeres": 306,
    "periodo": "Anual 2026",
    "lat": -34.53666519,
    "lon": -58.57874858,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Modalidad Técnico Profesional Secundaria - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "611264",
    "cueanexo": "061126400",
    "nombre": "INSTITUTO SAN JOAQUIN",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "SAN JUAN",
    "nro": "4570",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 11,
    "matricula": 176,
    "varones": 97,
    "mujeres": 79,
    "periodo": "Anual 2026",
    "lat": -34.54866843,
    "lon": -58.55005383,
    "turnos": "",
    "subvencion": "Sin Subvención",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "615667",
    "cueanexo": "061566700",
    "nombre": "INSTITUTO SAN JOSE",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "VILLA MAIPU",
    "calle": "ESTRADA",
    "nro": "2454",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 372,
    "varones": 168,
    "mujeres": 204,
    "periodo": "Anual 2026",
    "lat": -34.57064763,
    "lon": -58.52464095,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "603625",
    "cueanexo": "060362500",
    "nombre": "INSTITUTO SAN MARTÍN DE PORRES",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "JOSE LEON SUAREZ",
    "calle": "236",
    "nro": "1260",
    "desfavorabilidad": "1",
    "categoria": "Segunda",
    "secciones": 18,
    "matricula": 481,
    "varones": 234,
    "mujeres": 247,
    "periodo": "Anual 2026",
    "lat": -34.50466835,
    "lon": -58.58500953,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "608297",
    "cueanexo": "060829700",
    "nombre": "INSTITUTO SAN PIO X",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "136",
    "nro": "5070",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 15,
    "matricula": 410,
    "varones": 172,
    "mujeres": 238,
    "periodo": "Anual 2026",
    "lat": -34.55927293,
    "lon": -58.58028558,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "611236",
    "cueanexo": "061123600",
    "nombre": "INSTITUTO SANTA ANA",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "BOULEVARD BALLESTER",
    "nro": "4705",
    "desfavorabilidad": "0",
    "categoria": "Primera",
    "secciones": 18,
    "matricula": 595,
    "varones": 263,
    "mujeres": 332,
    "periodo": "Anual 2026",
    "lat": -34.54860241,
    "lon": -58.55156267,
    "turnos": "",
    "subvencion": "Subvención parcial 70%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "609958",
    "cueanexo": "060995800",
    "nombre": "NUESTRA SEÑORA DE LUJAN DEL BUEN VIAJE",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "BARRIO PARQUE GENERAL SAN MARTIN",
    "calle": "RUTA 8 CALLE MARCONI",
    "nro": "6725",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 384,
    "varones": 173,
    "mujeres": 211,
    "periodo": "Anual 2026",
    "lat": -34.56310905,
    "lon": -58.59329822,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "605784",
    "cueanexo": "060578400",
    "nombre": "NUESTRA SEÑORA DEL ROSARIO",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "GENERAL SAN MARTIN",
    "calle": "SAN CARLOS",
    "nro": "4609",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 12,
    "matricula": 168,
    "varones": 78,
    "mujeres": 90,
    "periodo": "Anual 2026",
    "lat": -34.5891149,
    "lon": -58.53621104,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "610709",
    "cueanexo": "061070900",
    "nombre": "SAGRADO CORAZON",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "GENERAL SAN MARTIN",
    "calle": "DR.RAMON CARRILLO",
    "nro": "2349",
    "desfavorabilidad": "0",
    "categoria": "Segunda",
    "secciones": 18,
    "matricula": 499,
    "varones": 190,
    "mujeres": 309,
    "periodo": "Anual 2026",
    "lat": -34.57420915,
    "lon": -58.54027154,
    "turnos": "",
    "subvencion": "Subvención Total 100%",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  },
  {
    "cue": "620302",
    "cueanexo": "062030200",
    "nombre": "TIERRA DE CRECIMIENTO",
    "gestion": "Privada",
    "modalidad": "Común",
    "localidad": "CIUDAD VILLA BALLESTER",
    "calle": "LACROZE",
    "nro": "5665",
    "desfavorabilidad": "0",
    "categoria": "Tercera",
    "secciones": 6,
    "matricula": 87,
    "varones": 60,
    "mujeres": 27,
    "periodo": "Anual 2026",
    "lat": -34.54296179,
    "lon": -58.56032054,
    "turnos": "",
    "subvencion": "Sin Subvención",
    "dependencia": "Dirección de Educación de Gestión Privada",
    "source": "Nivel secundario - Gestión privada 18-08-2026.xlsx"
  }
];
window.DATASET_META={
  "generated": "2026-08-18",
  "sources": [
    "Base estatal común validada",
    "Nivel secundario - Gestión privada 18-08-2026.xlsx",
    "Modalidad Técnico Profesional Secundaria - Gestión privada 18-08-2026.xlsx",
    "Modalidad Técnico Profesional Secundaria - Gestión estatal 18-08-2026.xlsx"
  ]
};
